---
- hosts: localhost
  connection: local
  tasks:
  - name: migration
    command: aws eks --region us-east-1 update-kubeconfig --name eks
    args:
      chdir: /home/lfcarrete/learn-terraform-aws-instance/app/ansible.yaml
  tasks:
  - name: migration
    command: kubectl apply -f /home/lfcarrete/learn-terraform-aws-instance/app/tese.yaml
    args:
      chdir: /home/lfcarrete/learn-terraform-aws-instance/app/ansible.yaml