---
- hosts: localhost
  connection: local
  tasks:
  - name: Setup
    command: aws eks --region us-east-1 update-kubeconfig --name eks
  - name: Sleep
    pause:
      seconds: 5
  - name: migration
    command: kubectl apply -f fastAPI.yaml
